### ISSUE TITLE
What do you think of the name Yurnalist?

### ISSUE THREAD

**Issue by 0x80** [0x80/yurnalist#5]
The code for this module is taken from ConsoleReporter in Yarn. Therefor I initially wanted to name the module `console-reporter`. It is pretty clear from that name what it does, but it doesn't sound very exciting.

A synonym for reporter is `journalist`, and I like that name, but of course it is already taken. Since we're literally borrowing the vast majority of code from Yarn, I think it is nice to make a reference to it and that's how I came up with the name `yurnalist`. 

The advantage of an ambiguous name like `yurnalist` is that the scope is not immediately fixed. For example if we decide to expose other reporters, like JSON, in addition to the console one, we easily could under the same name. 

A lot of times I find "cleaver" names to be annoying, so I'm wondering what you think. Do you prefer something plain like `console-reporter`? 

Respond with a 👍 if you like the name `yurnalist` or a 👎 if you think it is absolute rubbish.

If you have a better idea please leave your suggestion below 🙂.

**Comment by hsribei** [comment]
I'll try to think of suggestions and add one per comment for easier voting.

`clidx` -- from command-line interface & developer experience
